name: Branch Information Workflow

on:
  push:
  workflow_dispatch:

jobs:
  branch_info:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository (clone repo to runner VM)
    - name: CHECKOUT
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # WICHTIG: komplette Historie holen für Merge Info
    
    # Fetch all remote branches and ensure they are up-to-date
    - name: FETCH
      run: |
        git fetch --all
        git checkout -B main origin/main
    
    # Print all branches in the repo
    - name: ALL BRANCHES
      run: |
        echo "All branches in the repository:"
        git branch -a

    # Print all remote branches that are merged with main
    - name: MERGED
      run: |
        echo "Remote branches merged with main:"
        git branch -r --merged main
        
    # Print all remote branches that are not merged with main
    - name: NOT MERGED
      run: |
        echo "Remote branches NOT merged with main:"
        git branch -r --no-merged main

    # Give Merge Info about Branches: Loop 
    - name: MERGE INFO
      run: |
        for $branch in for-each-ref refs/remotes/origin/; do
          if git branch --merged main | grep -q "$branch"; then
            echo "✅ $branch is merged into main"
          else
            echo "❌ $branch is NOT merged into main"
          fi
        done
        
    - name: Print the date of the last commit for all branches merged with main
      run: |
        echo "Last commit date for merged branches:"
        git log -1 --format=%cd --date=short
