name: Branch Information Workflow

on:
  workflow_dispatch:

jobs:
  branch_info:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Print all branches in the repo
      run: |
        echo "All branches in the repository:"
        git branch -r

    - name: Print all branches that are merged with main
      run: |
        echo "Branches merged with main:"
        for branch in $(git branch -r | grep -v 'main' | sed 's/origin\///'); do
          if git merge-base --is-ancestor origin/main origin/$branch; then
            echo $branch
          fi
        done

    - name: Print all branches that are not merged with main
      run: |
        echo "Branches not merged with main:"
        for branch in $(git branch -r | grep -v 'main' | sed 's/origin\///'); do
          if ! git merge-base --is-ancestor origin/main origin/$branch; then
            echo $branch
          fi
        done

    - name: Print the date of the last commit for all branches merged with main
      run: |
        echo "Last commit date for merged branches:"
        for branch in $(git branch -r | grep -v 'main' | sed 's/origin\///'); do
          if git merge-base --is-ancestor origin/main origin/$branch; then
            last_commit_date=$(git log -1 --format="%cd" origin/$branch)
            echo "Branch: $branch - Last Commit Date: $last_commit_date"
          fi
        done
